name: Deploy

on:
  push:
    branches:
      - master

env:
  SERVER_HOST: s744875.smrtp.ru
  SERVER_USER: user744875
  SERVER_PATH: /var/www/user744875/data/www/ayu-dag.ru

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '18.x'

      # Install ssh key
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          node-version: '18.x'
          key: "${{ secrets.KEY }}"
          known_hosts: "unnecessary"

      # Adding Known Hosts
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts

      # Deploy
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{env.SERVER_HOST}}
          user: ${{env.SERVER_USER}}
          private_key: ${{secrets.KEY}}
          command: |
            cd ${{ env.SERVER_PATH }};
            git checkout master;
            git pull origin master